import React, { useState, useEffect } from 'react';
import { adminAPI } from '../../../api/client';
import styles from '../../../styles/pages/app/admin/VideoEngineControl.module.css';

export default function VideoEngineControl() {
  const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [videos, setVideos] = useState([]);
  const [cluster, setCluster] = useState({ nodes: 4, load: '45%' });
  const [newJob, setNewJob] = useState({ title: '', quality: '1080P FULL HD' });

  useEffect(() => {
    fetchJobs();
    const interval = setInterval(() => {
      setCluster(prev => ({ ...prev, load: `${Math.floor(Math.random() * 80 + 20)}%` }));
      fetchJobs();
    }, 2000);
    return () => clearInterval(interval);
  }, []);

  const fetchJobs = async () => {
    try {
      const response = await adminAPI.videoEngine.listJobs();
      setVideos(response.data.jobs || []);
    } catch (error) {
      console.error('Error fetching video jobs:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleCreateJob = async (e) => {
    e.preventDefault();
    try {
      await adminAPI.videoEngine.createJob(newJob);
      fetchJobs();
      setShowModal(false);
      setNewJob({ title: '', quality: '1080P FULL HD' });
    } catch (error) {
      alert('FAILED TO INITIALIZE RENDERING JOB');
    }
  };

  const handleAction = async (jobId, action) => {
    if (action === 'DELETE') {
      if (window.confirm('DELETE THIS JOB?')) {
        await adminAPI.videoEngine.deleteJob(jobId);
        fetchJobs();
      }
    } else {
      alert(`${action} TRIGGERED FOR JOB: ${jobId}`);
    }
  };

  return (
    <div className={styles.container + " animate-fadeIn"}>
      <div className="page-header">
        <div>
          <h1 className="page-title">VIDEO ENGINE CONTROL PANEL 🎥</h1>
          <p className="page-subtitle">MANAGE AUTOMATED STOCK VIDEO GENERATION PIPELINES AND RENDERING CLUSTERS.</p>
        </div>
        <button className="btn btn-primary btn-sm" onClick={() => setShowModal(true)}>➕ CREATE NEW JOB</button>
      </div>

      <div className={styles.engineGrid}>
        <div className={styles.card}>
          <div className={styles.cardHeader}>
            <h3>RENDER JOBS STATUS (LIVE)</h3>
          </div>
          <div className={styles.emptyArea}>
             <div style={{ fontSize: '1.5rem', transform: 'rotate(-5deg)' }}>🎬</div>
             <p style={{ fontSize: '0.65rem', fontWeight: 950, marginTop: 8 }}>{videos.filter(v => v.status === 'PROCESSING').length} ACTIVE JOBS IN QUEUE</p>
          </div>
          <button className="btn btn-sm btn-secondary btn-full" style={{ borderTop: '4px solid #000' }} onClick={() => alert('VIEWING FULL SYSTEM QUEUE...')}>VIEW QUEUE</button>
        </div>

        <div className={styles.card}>
          <div className={styles.cardHeader}>
             <h3>GPU RENDERING CLUSTER</h3>
          </div>
          <div className={styles.clusterStats}>
             <div className={styles.clusterItem}>
                <div className={styles.clusterValue} style={{ color: '#14a800' }}>{cluster.nodes}</div>
                <div className={styles.clusterLabel}>ONLINE NODES</div>
             </div>
             <div style={{ width: 3, height: 40, background: '#000' }}></div>
             <div className={styles.clusterItem}>
                <div className={styles.clusterValue} style={{ color: '#00A8FF' }}>{cluster.load}</div>
                <div className={styles.clusterLabel}>CLUSTER LOAD</div>
             </div>
          </div>
          <div style={{ display: 'flex', borderTop: '4px solid #000' }}>
             <button className="btn btn-sm btn-secondary" style={{ flex: 1, border: 'none' }} onClick={() => alert('MANAGING CLUSTER NODES...')}>MANAGE CLUSTER</button>
             <button className="btn btn-sm btn-secondary" style={{ flex: 1, borderLeft: '4px solid #000', borderTop: 'none', borderRight: 'none', borderBottom: 'none' }} onClick={() => alert('CLEARING ENGINE CACHE...')}>CLEAR CACHE</button>
          </div>
        </div>
      </div>

      <div className={styles.card}>
         <div className={styles.cardHeader} style={{ background: '#000' }}>
            <h3 style={{ color: '#fff' }}>RECENT GENERATED VIDEOS</h3>
         </div>
         <div className="table-responsive">
            <table className={styles.videoTable}>
               <thead>
                  <tr>
                     <th>VIDEO TITLE</th>
                     <th>JOB ID</th>
                     <th>GENERATED BY</th>
                     <th>DURATION</th>
                     <th>FORMAT</th>
                     <th>STATUS</th>
                     <th style={{ textAlign: 'center' }}>ACTIONS</th>
                  </tr>
               </thead>
               <tbody>
                  {videos.map(vid => (
                    <tr key={vid.id}>
                       <td><strong className="text-upper" style={{ fontSize: '0.75rem' }}>{vid.title}</strong></td>
                       <td><span style={{ fontSize: '0.6rem', fontWeight: 800 }}>{vid.id}</span></td>
                       <td><span className="badge badge-info" style={{ fontSize: '0.55rem' }}>{vid.user_name || 'SYSTEM'}</span></td>
                       <td><span style={{ fontWeight: 800 }}>{vid.duration}</span></td>
                       <td><span style={{ fontSize: '0.6rem', fontWeight: 950 }}>{vid.format}</span></td>
                       <td>
                          <span className={`${styles.statusBadge} ${vid.status === 'COMPLETED' ? styles.statusSuccess : vid.status === 'PROCESSING' ? styles.statusPending : styles.statusfailed}`}>
                            {vid.status}
                          </span>
                       </td>
                       <td>
                          <div style={{ display: 'flex', gap: 8, justifyContent: 'center' }}>
                             <button className="btn btn-sm btn-secondary" style={{ padding: '6px 14px', fontSize: '0.65rem' }} onClick={() => handleAction(vid.id, 'DOWNLOAD')}>DOWNLOAD</button>
                             <button className="btn btn-sm btn-secondary" style={{ padding: '6px 14px', fontSize: '0.65rem' }} onClick={() => handleAction(vid.id, 'DELETE')}>DELETE</button>
                          </div>
                       </td>
                    </tr>
                  ))}
               </tbody>
            </table>
         </div>
      </div>

      {showModal && (
        <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.5)', zIndex: 2000, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          <div style={{ background: '#fff', border: '4px solid #000', boxShadow: '8px 8px 0px #000', width: '90%', maxWidth: '400px' }}>
            <div style={{ background: 'var(--primary)', padding: '12px', borderBottom: '4px solid #000', display: 'flex', justifyContent: 'space-between' }}>
              <h2 style={{ margin: 0, fontSize: '0.9rem', fontWeight: 950 }}>CREATE NEW RENDERING JOB</h2>
              <button onClick={() => setShowModal(false)} style={{ background: 'none', border: 'none', fontWeight: 950, cursor: 'pointer' }}>×</button>
            </div>
            <form onSubmit={handleCreateJob} style={{ padding: '20px' }}>
              <div style={{ marginBottom: '16px' }}>
                <label style={{ display: 'block', fontWeight: 950, fontSize: '0.6rem', marginBottom: '6px' }}>VIDEO TITLE</label>
                <input 
                  className="form-control" 
                  style={{ width: '100%' }} 
                  required 
                  placeholder="E.G. MARKET RECAP" 
                  value={newJob.title}
                  onChange={(e) => setNewJob({...newJob, title: e.target.value})}
                />
              </div>
              <div style={{ marginBottom: '16px' }}>
                <label style={{ display: 'block', fontWeight: 950, fontSize: '0.6rem', marginBottom: '6px' }}>RENDER QUALITY</label>
                <select 
                  className="neo-select"
                  value={newJob.quality}
                  onChange={(e) => setNewJob({...newJob, quality: e.target.value})}
                >
                  <option>4K ULTRA HD</option>
                  <option>1080P FULL HD</option>
                  <option>720P HD</option>
                </select>
              </div>
              <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '12px', marginTop: '20px' }}>
                <button type="button" className="btn btn-sm btn-secondary" onClick={() => setShowModal(false)}>CANCEL</button>
                <button type="submit" className="btn btn-sm btn-primary">START RENDER</button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
